name=LC_MSP3526_T
version=1.0.0
author=jim lee
maintainer=MSP3526_T@leftcoast.biz
sentence=A set of tools to allow the Teensy version of the ST7796 320x480 display driver chip to run the left coast GUI.
paragraph=This is a set of tools for doing.. Well, what was said above.
category=Display
url=https://github.com/leftCoast/LC_MSP3526_T
architectures=*
depends=LC_baseTools,LC_SPI,LC_GUITools,ST7796_t3,Adafruit FT6206 Library
dot_a_linkage=true
