name=LC_MSP3526_T
version=1.0.0
author=jim lee
maintainer=MSP3526_T@leftcoast.biz
sentence=A set of tools to allow the Teensy version of the MSP3526 320x480 display to run the left coast GUI.
paragraph=This is a set of tools for doing.. Well, what was said above. BUT this in only designed to run on a Teensy processor. It's basied on code they (Teensy people) customaized.
category=Display
url=https://github.com/leftCoast/LC_MSP3526_T
architectures=*
depends=LC_baseTools,LC_SPI,LC_GUITools,ST7796_t3,Adafruit FT6206 Library
dot_a_linkage=true
